### ISSUE TITLE
Choosing between dominant/average

### ISSUE THREAD

**Issue by anta199** [sylvainjule/kirby-colorextractor#14] opened 2021-06-15 08:03 UTC
Hello,
First of all thanks for the great work on this.
I was wondering how nice would be to allow dominant/average color options to coexist in the same blueprint, allowing to choose between those two.
Is this something that can be achieved easily?

Thanks

**Comment by sylvainjule** [comment] 2021-12-07 14:50
Duplicate of #8, will follow through there.

**Closed by sylvainjule** 2021-12-07 14:50 UTC
